import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <header className='bg-slate-900 text-white'>
          <h1 className='text-3xl font-bold'>Header</h1>
        </header>
        {children}
        <footer className='bg-slate-900 text-white'>
          <h3 className='text-2xl font-bold'>Footer</h3>
        </footer>
      </body>
    </html>
  );
}
